[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"
  
[[constraint]]
  branch = "master"
  name = "github.com/matrix-org/gomatrix"

[[constraint]]
  name = "gopkg.in/gorp.v2"
  version = "2.1.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"
